### PR TITLE
Added Shopping_cart page

### LINKED ISSUE #16: Add shopping cart page, and a link to it in the navbar
Regards user story #2 
nothing needs to actually function just yet. Only an empty page that will eventually have a shopping cart. And a link to that page, ~preferably~ using a shopping cart IconButton in the navbar

see: 
- https://mui.com/components/icons/
- https://mui.com/components/material-icons/

### PR DESCRIPTION
**Pull request by longwaytogofromnow**
closes #16 
description-It will add a shopping_cart page.

### CODE REVIEW

**Comment by Kibuns** [comment]
great, but I would like to see an image of a shopping cart instead of "Shopping_cart" as text. This project uses [MUI](https://mui.com/) so take a look at [this](https://mui.com/components/icons/) for the icon button, and [this](https://mui.com/components/material-icons/) for a list of icons to choose from

**Comment by longwaytogofromnow** [comment]
Not a problem @Kibuns  i will give you an update once i will update the shopping_cart text as icon button.

**Comment by longwaytogofromnow** [comment]
@Kibuns updated the "Shopping_cart" text as icon button.
Plz review the changes and tell any further changes are required.

**Comment by Kibuns** [comment]
Great work, thank you!

**Comment by longwaytogofromnow** [comment]
This was my first PR so i am very happy to contribute to this project.
I would also like to thank you for your support.

**Pull request merged**
